// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7bxEw9IoXDifjt5PXPTIE8r6Y2CJsZtw',
    appId: '1:486323380246:web:3b2e286ec7bcaae54c5537',
    messagingSenderId: '486323380246',
    projectId: 'bootcampdatabase-8d011',
    authDomain: 'bootcampdatabase-8d011.firebaseapp.com',
    storageBucket: 'bootcampdatabase-8d011.appspot.com',
    measurementId: 'G-MCKTBL5GN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv5xqT7Sa8TNJr28CMo-2_ohglc-6yPZE',
    appId: '1:486323380246:android:56c38632f54b181f4c5537',
    messagingSenderId: '486323380246',
    projectId: 'bootcampdatabase-8d011',
    storageBucket: 'bootcampdatabase-8d011.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ-Un5D4OJ1xOxkQTSirRIe9j8K3ijXjI',
    appId: '1:486323380246:ios:32f2ee655e27b5024c5537',
    messagingSenderId: '486323380246',
    projectId: 'bootcampdatabase-8d011',
    storageBucket: 'bootcampdatabase-8d011.appspot.com',
    iosBundleId: 'com.example.flutterUpgrdeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ-Un5D4OJ1xOxkQTSirRIe9j8K3ijXjI',
    appId: '1:486323380246:ios:32f2ee655e27b5024c5537',
    messagingSenderId: '486323380246',
    projectId: 'bootcampdatabase-8d011',
    storageBucket: 'bootcampdatabase-8d011.appspot.com',
    iosBundleId: 'com.example.flutterUpgrdeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7bxEw9IoXDifjt5PXPTIE8r6Y2CJsZtw',
    appId: '1:486323380246:web:8d49ffc29c33e1454c5537',
    messagingSenderId: '486323380246',
    projectId: 'bootcampdatabase-8d011',
    authDomain: 'bootcampdatabase-8d011.firebaseapp.com',
    storageBucket: 'bootcampdatabase-8d011.appspot.com',
    measurementId: 'G-7Y3DWLTDTD',
  );
}
